#pragma once
#ifndef __PARSER_ENUM__
#define __PARSER_ENUM__
#define nb_keywords 37
#define nb_typeVariables 13
enum asmInstruction
{
  s8i,
  l8ui,
  l16ui,
  l16si,
  s16i,
  l32i,
  s32i,
  lsi,
  ssi,
  add,
  sub,
  quou,
  quos,
  mull,
  adds,
  subs,
  quous,
  muls,
  neg,
  negs

};

enum varTypeEnum
{
    __none__,
    __uint8_t__,
    __uint16_t__,
    __uint32_t__,
    __int__,
    __s_int__,
    __float__,
    __void__,
    __CRGB__,
    __CRGBW__,
    __char__,
    __Args__,
    __bool__,
    __userDefined__,
    __unknown__
};

enum tokenType
{
    TokenNumber,
    TokenAddition,
    TokenStar,
    TokenSubstraction,
    TokenOpenParenthesis,
    TokenCloseParenthesis,
    TokenOpenBracket,
    TokenCloseBracket,
    TokenOpenCurlyBracket,
    TokenCloseCurlyBracket,
    TokenEqual,
    TokenDoubleEqual,
    TokenIdentifier,
    TokenSemicolon,
    TokenUnknown,
    TokenSpace,
    TokenNewline,
    TokenEndOfFile,
    TokenSlash,
    TokenKeyword,
    TokenString,
    TokenExternal,
    TokenComma,
    TokenLessThan,
    TokenPlusPlus,
    TokenMinusMinus,
    TokenModulo,
    TokenLessOrEqualThan,
    TokenMoreThan,
    TokenMoreOrEqualThan,
    TokenNotEqual,
    TokenNot,
    TokenFunction,
    TokenUppersand,
    TokenDiese,
    TokenLineComment,
    TokenStartBlockComment,
    TokenEndBlockComment,
    TokenNegation,
    TokenShiftLeft,
    TokenShiftRight,
    TokenKeywordVarType,
    TokenKeywordExternalVar,
    TokenKeywordFor,
    TokenKeywordIf,
    TokenKeywordThen,
    TokenKeywordElse,
    TokenKeywordWhile,
    TokenKeywordReturn,
    TokenKeywordImport,
    TokenKeywordFrom,
    TokenKeywordASM,
    TokenKeywordDefine,
    TokenKeywordSafeMode,
    TokenKeywordHeader,
    TokenKeywordContent,
    TokenKeywordAnd,
    TokenKeywordOr,
    TokenPower,
    TokenKeywordContinue,
    TokenKeywordBreak,
    TokenKeywordFabs,
    TokenKeywordAbs,
    TokenKeywordSaveReg,
    TokenKeywordSaveRegAbs,
    TokenKeywordStruct,
    TokenUserDefinedName,
    TokenUserDefinedVariable,
    TokenMember,
    TokenUserDefinedVariableMember,
    TokenUserDefinedVariableMemberFunction,
    TokenDoubleUppersand,
    TokenDoubleOr,
    TokenQuestionMark,
    TokenColon,
    TokenPlusEqual,
    TokenMinusEqual,
    TokenStarEqual,
    TokenSlashEqual,
    TokenOverride

};


#endif